# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2nd.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import main
from selenium import webdriver
import tkinter as tk
from tkinter import filedialog,Tk,ttk,Button,messagebox
import os

NORM_FONT=("Hekvetuca",10)
class Ui_LCM_Main(object):
    glist=[]
    path=''
    def setupUi(self, LCM_Main):
        LCM_Main.setObjectName("LCM_Main")
        LCM_Main.resize(528, 786)
        LCM_Main.setFixedSize(538,786)
        LCM_Main.setStyleSheet("background-color: rgb(227, 231, 232);\n"
"background-color: rgb(51, 1, 112);")
        LCM_Main.setWindowIcon(QtGui.QIcon('icon.jpg'))
        
        self.centralwidget = QtWidgets.QWidget(LCM_Main)
        self.centralwidget.setObjectName("centralwidget")
        self.baseFrame = QtWidgets.QFrame(self.centralwidget)
        self.baseFrame.setGeometry(QtCore.QRect(-10, -40, 651, 881))
        self.baseFrame.setStyleSheet("background-color: rgb(51, 1, 112);")
        self.baseFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.baseFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.baseFrame.setObjectName("baseFrame")
        self.frame_Top = QtWidgets.QFrame(self.baseFrame)
        self.frame_Top.setGeometry(QtCore.QRect(0, 90, 651, 141))
        self.frame_Top.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_Top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Top.setObjectName("frame_Top")
        self.label = QtWidgets.QLabel(self.frame_Top)
        self.label.setGeometry(QtCore.QRect(360, 30, 401, 71))
        self.label.setStyleSheet("font: 50pt \"Franklin Gothic Medium Cond\";\n"
"color: rgb(51, 0, 114);")
        self.label.setObjectName("label")
        self.label_logo = QtWidgets.QLabel(self.frame_Top)
        self.label_logo.setGeometry(QtCore.QRect(0, 0, 431, 131))
        self.label_logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("C://Users//Cheng Shi//Desktop//317/laurier-logo.png"))
        self.label_logo.setObjectName("label_logo")
        self.label_logo.raise_()
        self.label.raise_()
        self.frame_Lower = QtWidgets.QFrame(self.baseFrame)
        self.frame_Lower.setGeometry(QtCore.QRect(30, 490, 491, 301))
        self.frame_Lower.setStyleSheet("background-color: rgb(242, 242, 242);\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;")
        self.frame_Lower.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Lower.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Lower.setObjectName("frame_Lower")
        self.pB_Load = QtWidgets.QPushButton(self.frame_Lower)
        self.pB_Load.setGeometry(QtCore.QRect(40, 210, 411, 61))
        self.pB_Load.setStyleSheet("QPushButton {\n"
"    font: 40 18pt \"Stencil\";\n"
"    color: #330170;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ebaa1c, stop: 1 #f5c503\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e18f09, stop: 1 #da9024\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #da9024, stop: 1  #da9024\n"
"        );\n"
"    }")
        self.pB_Load.setObjectName("pB_Load")
        self.pB_Gen = QtWidgets.QPushButton(self.frame_Lower)
        self.pB_Gen.setGeometry(QtCore.QRect(40, 120, 411, 61))
        self.pB_Gen.setStyleSheet("QPushButton {\n"
"    font: 40 18pt \"Stencil\";\n"
"    color: #330170;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ebaa1c, stop: 1 #f5c503\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e18f09, stop: 1 #da9024\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #da9024, stop: 1  #da9024\n"
"        );\n"
"    }")
        self.pB_Gen.setObjectName("pB_Gen")
        self.pB_Login = QtWidgets.QPushButton(self.frame_Lower)
        self.pB_Login.setGeometry(QtCore.QRect(40, 30, 411, 61))
        self.pB_Login.setStyleSheet("QPushButton {\n"
"    font: 40 18pt \"Stencil\";\n"
"    color: #330170;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ebaa1c, stop: 1 #f5c503\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e18f09, stop: 1 #da9024\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #da9024, stop: 1  #da9024\n"
"        );\n"
"    }")
        self.pB_Login.setObjectName("pB_Login")
        self.pB_Load.raise_()
        self.pB_Load.raise_()
        self.pB_Gen.raise_()
        self.pB_Login.raise_()
        self.frame_Upper = QtWidgets.QFrame(self.baseFrame)
        self.frame_Upper.setGeometry(QtCore.QRect(30, 270, 491, 171))
        self.frame_Upper.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;")
        self.frame_Upper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Upper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Upper.setObjectName("frame_Upper")
        self.label_3 = QtWidgets.QLabel(self.frame_Upper)
        self.label_3.setGeometry(QtCore.QRect(60, 30, 361, 101))
        self.label_3.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(242, 188, 12);\n"
"border-top-color: rgb(242, 188, 12);\n"
"alternate-background-color: rgb(242, 188, 12);\n"
"selection-color: rgb(242, 188, 12);\n"
"gridline-color: rgb(242, 188, 12);\n"
"border-color: rgb(242, 188, 12);\n"
"background-color: rgb(242, 188, 12);\n"
"font: 40 15pt \"Stencil\";\n"
"color: rgb(51, 1, 112);\n"
"border-style: 0")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame_Upper)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 471, 151))
        self.label_2.setStyleSheet("background-color: rgb(242, 188, 12);\n"
"border-style: outset")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label_3.raise_()
        self.frame_Upper.raise_()
        self.frame_Lower.raise_()
        self.frame_Top.raise_()
        LCM_Main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LCM_Main)
        self.statusbar.setObjectName("statusbar")
        LCM_Main.setStatusBar(self.statusbar)

        self.retranslateUi(LCM_Main)
        QtCore.QMetaObject.connectSlotsByName(LCM_Main)
    def login(self):
        self.glist=main.login()

    def gen_ics(self,list):
        if len(list)==0:
                root = Tk()
                root.withdraw()
                messagebox.showerror("Error","Please login first")
        else:
                root =Tk()
                root.withdraw()
                self.path = filedialog.askdirectory()
                main.gen(list,self.path)
                messagebox.showinfo("Finished", "ICS file generated!")

    def load_ics(self):
            root =Tk()
            root.withdraw()
            self.path=filedialog.askopenfilename(filetypes=(('ics files','ics'),))
            if(self.path[-3:]!='ics'):
                    messagebox.showerror("Error","Please select ics file")

            else:
                print(self.path)
                path = self.path
                os.startfile(path)
            
    def retranslateUi(self, LCM_Main):
        _translate = QtCore.QCoreApplication.translate
        LCM_Main.setWindowTitle(_translate("LCM_Main", "L.C.M"))
        self.label.setText(_translate("LCM_Main", "L.C.M"))
        self.pB_Load.setText(_translate("LCM_Main", "Load ics file"))
        self.pB_Load.clicked.connect(self.load_ics)
        self.pB_Gen.setText(_translate("LCM_Main", "Generate ICS FILE"))
        self.pB_Gen.clicked.connect(lambda:self.gen_ics(self.glist))
        self.pB_Login.setText(_translate("LCM_Main", "Login to Loris"))
        self.pB_Login.clicked.connect(self.login)
        self.label_3.setText(_translate("LCM_Main", "                 Welcome to\n"
"                         the\n"
"  Laurier Calendar Maker"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LCM_Main = QtWidgets.QMainWindow()
    ui = Ui_LCM_Main()
    ui.setupUi(LCM_Main)
    LCM_Main.show()
    sys.exit(app.exec_())
